name: proyecto-sprint-11
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.5
  - numpy>=1.23
  - scikit-learn>=1.2
  - matplotlib>=3.6
  - seaborn>=0.12
  - jupyter
  - ipykernel
  - pip
